### ISSUE TITLE
Rhino Parse Warning (Trailing comma is not legal in an ECMA-262 object initializer

### ISSUE THREAD

**Issue by khusamov** [khusamov/extjs#5]
[WRN] C1000: Rhino Parse Warning (Trailing comma is not legal in an ECMA-262 object initializer =>

```
      });) -- /khusamov-svg/src/Svg.js:61:2
 });) -- /khusamov-svg/src/desktop/Panel.js:58:1
              }) -- /khusamov-svg/src/desktop/surface/Surface.js:22:3
     },) -- /khusamov-svg/src/desktop/surface/Surface.js:65:5
 });) -- /khusamov-svg/src/element/Element.js:552:1
 }, function(Path) {) -- /khusamov-svg/src/element/Path.js:52:1
      },) -- /khusamov-svg/src/element/attribute/transform/Filter.js:75:2
      },) -- /khusamov-svg/src/geometry/Arc.js:69:2
      ],) -- /khusamov-svg/src/geometry/Line.js:14:2
      },) -- /khusamov-svg/src/geometry/Primitive.js:67:2
      },) -- /khusamov-svg/src/geometry/equation/Linear.js:109:2
 });) -- /khusamov-svg/src/geometry/equation/Linear.js:402:1
 });) -- /khusamov-svg/src/geometry/path/____temp/Arc.js:86:1
      },) -- /khusamov-svg/src/geometry/path/____temp/Command.js:76:2
 }, function(Command) {) -- /khusamov-svg/src/geometry/path/____temp/Command.js:125:1
 });) -- /khusamov-svg/src/geometry/path/____temp/Move.js:43:1
 }, function(Vector) {) -- /khusamov-svg/src/geometry/vector/Vector.js:197:1
 });) -- /khusamov-svg/src/layout/Svg.js:45:1
```

**Comment by narasam** [comment]
Hello. I am getting same error and could not solve .Is there anyone knows why this error comes

[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\AddEmployee.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\AddEmployee.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\AddEmployee.js
[INF] -----------------------
[WRN] C1000: Rhino Parse Warning (Trailing comma is not legal in an ECMA-262 obj
ect initializer =>                   ],) -- D:\SenchaTrainingDocument\sencha_wor
kshop\devon4sencha\demo\app\view\employee\AddEmployee.js:59:19
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] merging 249 input resources into D:\SenchaTrainingDocument\sencha_workshop
\devon4sencha\build\development\demo\resources
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo\resources
[INF] merging 10 input resources into D:\SenchaTrainingDocument\sencha_workshop\
devon4sencha\build\development\demo
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.json
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.js
[INF] writing sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[LOG] Building D:/SenchaTrainingDocument/sencha_workshop/devon4sencha/build/temp
/development/demo/sass/demo-all.scss
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] Refresh complete in 11 sec. at 11:27:10 AM
[INF] -----------------------
[INF] Waiting for changes...
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] -----------------------
[ERR] Failed to resolve dependency demo.Application for file demo.app.$Applicati
on
[ERR]
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.ExNotFound: Unknown definition for dependency : demo
.Application
[ERR]   at java.lang.re
[ERR] flect.Method.invoke(Unknown Source)
[ERR]
[ERR] Total time: 26 minutes 6 seconds
[ERR] Error during rebuild : The following error occurred while executing this l
ine:
D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\demo\.sencha\app\watch-im
pl.xml:4: The following error occurred while executing this line:
D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\demo\.sencha\app\build-im
pl.xml:380: The following error occurred while executing this line:
D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\demo\.sencha\app\init-imp
l.xml:382: com.sencha.exceptions.ExNotFound: Unknown definition for dependency :
 demo.Application
[INF] Refresh complete in 0 sec. at 11:32:31 AM
[INF] -----------------------
[INF] Waiting for changes...
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] -----------------------
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] merging 249 input resources into D:\SenchaTrainingDocument\sencha_workshop
\devon4sencha\build\development\demo\resources
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo\resources
[INF] merging 10 input resources into D:\SenchaTrainingDocument\sencha_workshop\
devon4sencha\build\development\demo
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.json
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.js
[INF] writing sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[LOG] Building D:/SenchaTrainingDocument/sencha_workshop/devon4sencha/build/temp
/development/demo/sass/demo-all.scss
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] Refresh complete in 10 sec. at 11:32:43 AM
[INF] -----------------------
[INF] Waiting for changes...
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] -----------------------
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] merging 249 input resources into D:\SenchaTrainingDocument\sencha_workshop
\devon4sencha\build\development\demo\resources
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo\resources
[INF] merging 10 input resources into D:\SenchaTrainingDocument\sencha_workshop\
devon4sencha\build\development\demo
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.json
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.js
[INF] writing sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[LOG] Building D:/SenchaTrainingDocument/sencha_workshop/devon4sencha/build/temp
/development/demo/sass/demo-all.scss
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] Refresh complete in 11 sec. at 11:33:36 AM
[INF] -----------------------
[INF] Waiting for changes...
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] -----------------------
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] merging 249 input resources into D:\SenchaTrainingDocument\sencha_workshop
\devon4sencha\build\development\demo\resources
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo\resources
[INF] merging 10 input resources into D:\SenchaTrainingDocument\sencha_workshop\
devon4sencha\build\development\demo
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.json
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.js
[INF] writing sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[LOG] Building D:/SenchaTrainingDocument/sencha_workshop/devon4sencha/build/temp
/development/demo/sass/demo-all.scss
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] Refresh complete in 10 sec. at 11:33:48 AM
[INF] -----------------------
[INF] Waiting for changes...
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] Detected change to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\app\view\employee\EmployeeV.js
[INF] -----------------------
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] merging 249 input resources into D:\SenchaTrainingDocument\sencha_workshop
\devon4sencha\build\development\demo\resources
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo\resources
[INF] merging 10 input resources into D:\SenchaTrainingDocument\sencha_workshop\
devon4sencha\build\development\demo
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.json
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.js
[INF] writing sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[LOG] Building D:/SenchaTrainingDocument/sencha_workshop/devon4sencha/build/temp
/development/demo/sass/demo-all.scss
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] Refresh complete in 16 sec. at 11:34:05 AM
[INF] -----------------------
[INF] Waiting for changes...
^C
D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\demo>
D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\demo>
D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\demo>
D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\demo>
D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\demo>sencha app watch
Sencha Cmd v6.1.2.15
[INF] Processing Build Descriptor : default
[INF] Starting server on port : 1841
[INF] Mapping http://localhost:1841/~cmd to D:\TrainingProject\software\Sencha\C
md\default\6.1.2.15...
[INF] Mapping http://localhost:1841/ to D:\SenchaTrainingDocument\sencha_worksho
p\devon4sencha...
[INF] Application available at http://localhost:1841
[INF] Loading app json manifest...
[WRN] C1000: Rhino Parse Warning (Trailing comma is not legal in an ECMA-262 obj
ect initializer => });) -- D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\app\controller\table\TableController.js:144:1
[WRN] C1000: Rhino Parse Warning (Trailing comma is not legal in an ECMA-262 obj
ect initializer =>                   ],) -- D:\SenchaTrainingDocument\sencha_wor
kshop\devon4sencha\demo\app\view\employee\AddEmployee.js:59:19
[WRN] C1000: Rhino Parse Warning (Trailing comma is not legal in an ECMA-262 obj
ect initializer =>                   ],) -- D:\SenchaTrainingDocument\sencha_wor
kshop\devon4sencha\demo\app\view\order\AddOrder.js:65:19
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] merging 249 input resources into D:\SenchaTrainingDocument\sencha_workshop
\devon4sencha\build\development\demo\resources
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo\resources
[INF] merging 10 input resources into D:\SenchaTrainingDocument\sencha_workshop\
devon4sencha\build\development\demo
[INF] merged 0 resources into D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\development\demo
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.json
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\sass\example\bootstrap.js
[INF] writing sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4se
ncha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[INF] appending sass content to D:\SenchaTrainingDocument\sencha_workshop\devon4
sencha\build\temp\development\demo\sass\demo-all.scss.tmp
[LOG] Building D:/SenchaTrainingDocument/sencha_workshop/devon4sencha/build/temp
/development/demo/sass/demo-all.scss
[INF] Appending content to D:\SenchaTrainingDocument\sencha_workshop\devon4sench
a\demo\bootstrap.js
[INF] Writing content to D:\SenchaTrainingDocument\sencha_workshop\devon4sencha\
demo\bootstrap.json
[INF] Waiting for changes...

**Comment by khusamov** [comment]
You refer to the Sencha Forum https://www.sencha.com/forum/forumdisplay.php?133-Ext-6-Q-amp-A
